### PR TITLE
sig-security proposal

### PR DESCRIPTION
**Pull request by nyrahul**
Proposal based on the TSC discussion on Sep 14th 2023:
* [Minutes](https://wiki.nephio.org/download/attachments/21685184/_Nephio-TSC-2023-09-14.txt?version=1&modificationDate=1694722906792&api=v2)
* [recording](https://wiki.nephio.org/download/attachments/21685184/GMT20230914-165607_Recording_3840x2160.mp4?version=1&modificationDate=1694722602841&api=v2)
* [TSC Meeting Content](https://wiki.nephio.org/display/HOME/Technical+Steering+Committee+%28TSC%29+Meetings+Content)

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@KennyPaul please confirm that the TSC vote passed, and I can merge this.

**Comment by KennyPaul** [comment]
@johnbelamaric - yes the TSC vote for the creation of the security SIG passed: https://lists.nephio.org/g/nephio-tsc/message/177 
-kenny

**Pull request merged**
