### PR TITLE
Add Samsung into the contributors list

### PR DESCRIPTION
**Pull request by electrocucaracha**

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@electrocucaracha I think there are some other folks that helped on the UI in R1. Are they able to continue with contributions?

**Comment by electrocucaracha** [comment]
> @electrocucaracha I think there are some other folks that helped on the UI in R1. Are they able to continue with contributions?

@johnbelamaric good question, let me double-check that

**Comment by johnbelamaric** [comment]
In general, I think we probably want to retire this list here and just use the GitHub org and OWNERS files as the system of record for contributors. But I think that is up to @nephio-project/sig-release to figure out when/how to do that.

**Comment by johnbelamaric** [comment]
(no owners file, merging manually)

**Pull request merged**
